[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install uv", "uv pip install --system -r requirements.txt"]

[start]
cmd = "uv run -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"