# Nixpacks configuration for Railway deployment
[providers]
python = "3.11"

[build]
# Install full dependencies for all features (AI, IB, etc.)
install_cmd = "pip install -r requirements.txt"

[start]
# Start the full API application
cmd = "python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"