[build]
# Use nixpacks (Railway's default) instead of Dockerfile
# This is the simplest, most reliable approach

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
# Railway will automatically detect and run the start command