#!/bin/bash

# Development Startup Script for Trade Strategies
# This script starts both frontend and backend services
# Generated by Agent OS to prevent setup amnesia

set -e  # Exit on error

echo "🚀 Starting Trade Strategies Development Environment"
echo "================================================="

# Load environment variables
if [ -f .env ]; then
    echo "📋 Loading backend environment from .env"
    export $(grep -v '^#' .env | xargs)
fi

if [ -f .env.local ]; then
    echo "📋 Loading frontend environment from .env.local"
    export $(grep -v '^#' .env.local | xargs)
fi

# Get ports from environment or use defaults
BACKEND_PORT=${API_PORT:-${PORT:-8000}}
FRONTEND_PORT=${PORT:-3000}

# Backend startup
echo ""
echo "📡 Starting Backend Server on port $BACKEND_PORT..."
cd backend 2>/dev/null || echo "Backend directory will be created in Phase 1"

if [ -d . ] && [ -f "main.py" ]; then
    source .venv/bin/activate || uv venv && source .venv/bin/activate
    uv pip install -r requirements.txt 2>/dev/null || echo "Requirements.txt will be created in Phase 1"
    uv run uvicorn main:app --reload --port $BACKEND_PORT &
else
    echo "⚠️  Backend not yet implemented - will be created in Phase 1"
fi

# Frontend startup  
echo ""
echo "🎨 Starting Frontend Server..."
# Navigate back to project root where React app is located
cd .. 2>/dev/null || cd . 2>/dev/null

if [ -f "package.json" ]; then
    echo "✅ React frontend found - starting on default Vite port (5173)"
    npm install 2>/dev/null || echo "Dependencies already installed"
    npm run dev &
    FRONTEND_PORT=5173  # Vite default port
else
    echo "⚠️  Frontend package.json not found"
fi

echo ""
echo "✅ Development environment status:"
echo "   ✅ React Frontend: http://localhost:$FRONTEND_PORT (operational!)"
echo "   ⚠️  Backend API:   http://localhost:$BACKEND_PORT (coming in Phase 1)"
echo ""
echo "📋 Current Status: Phase 1 Progress - React Frontend Complete!"
echo "   🎯 React app working with TypeScript, Tailwind, Framer Motion"
echo "   📊 Legacy scripts: python backtest_strategies.py --help"
echo ""
echo "Press Ctrl+C to stop all services"
wait