#!/bin/bash

# Development Startup Script for Trade Strategies
# This script starts both frontend and backend services
# Generated by Agent OS to prevent setup amnesia

set -e  # Exit on error

echo "🚀 Starting Trade Strategies Development Environment"
echo "================================================="

# Load environment variables
if [ -f .env ]; then
    echo "📋 Loading backend environment from .env"
    export $(grep -v '^#' .env | xargs)
fi

if [ -f .env.local ]; then
    echo "📋 Loading frontend environment from .env.local"
    export $(grep -v '^#' .env.local | xargs)
fi

# Get ports from environment or use defaults
BACKEND_PORT=${API_PORT:-${PORT:-8000}}
FRONTEND_PORT=${PORT:-3000}

# Backend startup
echo ""
echo "📡 Starting Backend Server on port $BACKEND_PORT..."
cd backend 2>/dev/null || echo "Backend directory will be created in Phase 1"

if [ -d . ] && [ -f "main.py" ]; then
    source .venv/bin/activate || uv venv && source .venv/bin/activate
    uv pip install -r requirements.txt 2>/dev/null || echo "Requirements.txt will be created in Phase 1"
    uv run uvicorn main:app --reload --port $BACKEND_PORT &
else
    echo "⚠️  Backend not yet implemented - will be created in Phase 1"
fi

# Frontend startup  
echo ""
echo "🎨 Starting Frontend Server on port $FRONTEND_PORT..."
cd ../frontend 2>/dev/null || cd .. 2>/dev/null || echo "Frontend directory will be created in Phase 1"

if [ -d . ] && [ -f "package.json" ]; then
    npm install
    npm run dev &
else
    echo "⚠️  Frontend not yet implemented - will be created in Phase 1"
fi

echo ""
echo "✅ Development environment setup complete!"
echo "   Frontend: http://localhost:$FRONTEND_PORT (when implemented)"
echo "   Backend:  http://localhost:$BACKEND_PORT (when implemented)"
echo ""
echo "📋 Current Status: Phase 0 (Legacy Python scripts available)"
echo "   Run legacy scripts: python backtest_strategies.py --help"
echo ""
echo "Press Ctrl+C to stop all services"
wait