"""Add AI assessment tables for GPT-5 integration

Revision ID: 66fb0f864ac9
Revises: 87bc83f32a13
Create Date: 2025-08-11 05:55:06.066907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fb0f864ac9'
down_revision: Union[str, None] = '87bc83f32a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_backtests_dates', table_name='backtests')
    op.drop_index('idx_backtests_strategy', table_name='backtests')
    op.drop_index('idx_backtests_timeframe', table_name='backtests')
    op.drop_index('idx_strategies_params', table_name='strategies', postgresql_using='gin')
    op.drop_index('idx_trades_pnl', table_name='trades', postgresql_where='(realized_pnl IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trades_pnl', 'trades', ['realized_pnl'], unique=False, postgresql_where='(realized_pnl IS NOT NULL)')
    op.create_index('idx_strategies_params', 'strategies', ['parameters'], unique=False, postgresql_using='gin')
    op.create_index('idx_backtests_timeframe', 'backtests', ['timeframe'], unique=False)
    op.create_index('idx_backtests_strategy', 'backtests', ['strategy_id'], unique=False)
    op.create_index('idx_backtests_dates', 'backtests', ['start_date', 'end_date'], unique=False)
    # ### end Alembic commands ###
