"""Add SPY price fields to market_data_snapshots table

Revision ID: b4855c4e558a
Revises: a2f803e05360
Create Date: 2025-08-13 15:52:34.819921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4855c4e558a'
down_revision: Union[str, None] = 'a2f803e05360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data_snapshots', sa.Column('spy_price', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('market_data_snapshots', sa.Column('spy_change', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('market_data_snapshots', sa.Column('spy_change_percent', sa.DECIMAL(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_data_snapshots', 'spy_change_percent')
    op.drop_column('market_data_snapshots', 'spy_change')
    op.drop_column('market_data_snapshots', 'spy_price')
    # ### end Alembic commands ###
